# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/william/myfile/TODO/2Graduation/FSeedCodeB/FSeedCB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/william/myfile/TODO/2Graduation/FSeedCodeB/FSeedCB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/william/myfile/TODO/2Graduation/FSeedCodeB/FSeedCB/CMakeFiles /media/william/myfile/TODO/2Graduation/FSeedCodeB/FSeedCB/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/william/myfile/TODO/2Graduation/FSeedCodeB/FSeedCB/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FSeedCB

# Build rule for target.
FSeedCB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FSeedCB
.PHONY : FSeedCB

# fast build rule for target.
FSeedCB/fast:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/build
.PHONY : FSeedCB/fast

http.o: http.c.o

.PHONY : http.o

# target to build an object file
http.c.o:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/http.c.o
.PHONY : http.c.o

http.i: http.c.i

.PHONY : http.i

# target to preprocess a source file
http.c.i:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/http.c.i
.PHONY : http.c.i

http.s: http.c.s

.PHONY : http.s

# target to generate assembly for a file
http.c.s:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/http.c.s
.PHONY : http.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/main.c.s
.PHONY : main.c.s

rio.o: rio.c.o

.PHONY : rio.o

# target to build an object file
rio.c.o:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/rio.c.o
.PHONY : rio.c.o

rio.i: rio.c.i

.PHONY : rio.i

# target to preprocess a source file
rio.c.i:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/rio.c.i
.PHONY : rio.c.i

rio.s: rio.c.s

.PHONY : rio.s

# target to generate assembly for a file
rio.c.s:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/rio.c.s
.PHONY : rio.c.s

signal.o: signal.c.o

.PHONY : signal.o

# target to build an object file
signal.c.o:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/signal.c.o
.PHONY : signal.c.o

signal.i: signal.c.i

.PHONY : signal.i

# target to preprocess a source file
signal.c.i:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/signal.c.i
.PHONY : signal.c.i

signal.s: signal.c.s

.PHONY : signal.s

# target to generate assembly for a file
signal.c.s:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/signal.c.s
.PHONY : signal.c.s

threadpool.o: threadpool.c.o

.PHONY : threadpool.o

# target to build an object file
threadpool.c.o:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/threadpool.c.o
.PHONY : threadpool.c.o

threadpool.i: threadpool.c.i

.PHONY : threadpool.i

# target to preprocess a source file
threadpool.c.i:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/threadpool.c.i
.PHONY : threadpool.c.i

threadpool.s: threadpool.c.s

.PHONY : threadpool.s

# target to generate assembly for a file
threadpool.c.s:
	$(MAKE) -f CMakeFiles/FSeedCB.dir/build.make CMakeFiles/FSeedCB.dir/threadpool.c.s
.PHONY : threadpool.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FSeedCB"
	@echo "... http.o"
	@echo "... http.i"
	@echo "... http.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... rio.o"
	@echo "... rio.i"
	@echo "... rio.s"
	@echo "... signal.o"
	@echo "... signal.i"
	@echo "... signal.s"
	@echo "... threadpool.o"
	@echo "... threadpool.i"
	@echo "... threadpool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

